apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: my-cluster-issuer # replace with some valid issuer
spec:
  gatewayClassName: nginx
  listeners:
  - name: http # the gatway listens on http, but redirects to https
    port: 80
    protocol: HTTP
  - name: https
    port: 443
    protocol: HTTPS
    hostname: messageapp
    tls:
      mode: Terminate
      certificateRefs:
      - name: messageapp-cert
---
# Route https traffic to corresponding services
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route
spec:
  parentRefs:
  - name: gateway
  #  sectionName: https
  hostnames:
  - "messageapp"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /Auth
    backendRefs:
    - name: auth-service-clusterip
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /Message
    backendRefs:
    - name: message-service-clusterip
      port: 80
---
