apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-real-time-deployment
  labels:
    app: message-real-time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-real-time
  template:
    metadata:
      labels:
        app: message-real-time
    spec:
      containers:
      - name: message-real-time
        image: jmstoledo/message-real-time:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: secrets
        projected:
          sources:
          - secret:
              name: jwt-settings
          - secret:
              name: db-settings
---
apiVersion: v1
kind: Service
metadata:
  name: message-real-time-clusterip
spec:
  type: ClusterIP
  selector:
    app: message-real-time
  ports:
  - name: message-real-time
    protocol: TCP
    port: 80
    targetPort: 8080