apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms-deployment
  labels:
    app: rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
      - name: rooms
        image: jmstoledo/rooms:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: secrets
        projected:
          sources:
          - secret:
              name: jwt-settings
          - secret:
              name: db-settings
---
apiVersion: v1
kind: Service
metadata:
  name: rooms-clusterip
spec:
  type: ClusterIP
  selector:
    app: rooms
  ports:
  - name: rooms
    protocol: TCP
    port: 80
    targetPort: 8080